DB_USERNAME = "Abhiram"
DB_TOKEN = "bayzam@123"

[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "database"
username = "root"
password = "Bayzam@123"
query = { charset = "utf8mb4" }